### ISSUE TITLE
Horário não está de acordo com o Horário de Verão

### ISSUE THREAD

**Issue by brunochaves** [camilocarlos/toggl_export_web#1]
No relatório gerado, os horários não estão seguindo o horário de verão.

**Comment by camilocarlos** [comment]
@brunochaves , a resposta da API do Toggl não fornece a Timezone no qual a Time Entry foi registrada. Exemplo : 
```javascript
{u'at': u'2016-10-14T21:53:24+00:00',
 u'billable': True,
 u'description': u'Suporte SIAFE-Rio',
 u'duration': 16680,
 u'duronly': False,
 u'guid': u'51ad35f8-4dd0-4798-8a6b-79581b873140',
 u'id': 463454900,
 u'pid': 5735835,
 u'start': u'2016-10-14T17:16:00+00:00',
 u'stop': u'2016-10-14T21:54:00+00:00',
 u'uid': 1055560,
 u'wid': 653247}

```
Com isso, a solução adotada foi considerar o dia do horário de verão, e caso o registro seja anterior ao horário de verão, é aplicado UTC+03:00, senão é considerado UTC+02:00. Uma melhoria seria obter o UTC do profile do usuário.

[]s
Camilo
